version: 2

models:
  - name: stg_stations
    description: >
      Raw monitoring station data from the [Environment Agency real-time flood monitoring API](https://environment.data.gov.uk/flood-monitoring/doc/reference#introduction).


      One row per station. Columns retain original JSON types.


      🔗 [API docs](https://environment.data.gov.uk/flood-monitoring/doc/reference#stations)

  - name: stg_measures
    description: >
      Raw measure data from the [Environment Agency real-time flood monitoring API](https://environment.data.gov.uk/flood-monitoring/doc/reference#introduction).


      Each measure represents a specific type of reading (e.g. river level, rainfall)
      at a specific station. URL prefixes on foreign keys are stripped at this layer.


      🔗 [API docs](https://environment.data.gov.uk/flood-monitoring/doc/reference#measures)

  - name: stg_readings
    description: >
      Raw readings from the [Environment Agency real-time flood monitoring API](https://environment.data.gov.uk/flood-monitoring/doc/reference#introduction) (`?latest` endpoint).


      Each row is a single measurement value at a point in time.


      NOTE: This is a snapshot -- only the most recent readings are returned by the API.
      URL prefixes on foreign keys are stripped at this layer.

      🔗 [API docs](https://environment.data.gov.uk/flood-monitoring/doc/reference#readings)

unit_tests:
  - name: test_stg_readings_value_extraction
    description: Verify JSON array values extract first element, scalars pass through
    model: stg_readings
    given:
      - input: source('env_agency', 'raw_readings')
        rows:
          - {
              items:
                [
                  {
                    dateTime: "2025-01-01 00:00:00",
                    measure: "http://environment.data.gov.uk/flood-monitoring/id/measures/scalar-test",
                    value: 3.5,
                  },
                ],
            }
          - {
              items:
                [
                  {
                    dateTime: "2025-01-01 00:00:01",
                    measure: "http://environment.data.gov.uk/flood-monitoring/id/measures/array-test",
                    value: [1.5, 2.0],
                  },
                ],
            }
          - {
              items:
                [
                  {
                    dateTime: "2025-01-01 00:00:02",
                    measure: "http://environment.data.gov.uk/flood-monitoring/id/measures/negative-array",
                    value: [-52.984, 1.016],
                  },
                ],
            }
    expect:
      rows:
        - {
            dateTime: "2025-01-01 00:00:00",
            measure: "scalar-test",
            value: 3.5,
          }
        - { dateTime: "2025-01-01 00:00:01", measure: "array-test", value: 1.5 }
        - {
            dateTime: "2025-01-01 00:00:02",
            measure: "negative-array",
            value: -52.984,
          }
