SELECT r.dateTime,
r.measure,
r.value,
m.datumType,
m.label AS m_label,
m.parameter,
m.parameterName,
m.period,
m.qualifier,
m.unit,
m.unitName,
m.valueType,
m.station,
s.RLOIid,
s.catchmentName,
s.dateOpened,
s.easting,
s.label AS s_label,
s.latitude,
s.longitude,
s.northing,
s.riverName,
s.stageScale,
s.stationReference,
s.status,
s.town,
s.wiskiID,
s.datumOffset,
s.gridReference,
s.downstageScale,

FROM {{ ref('fct_readings') }}  r
LEFT OUTER JOIN {{ ref('dim_measures') }} m ON r.measure = m.notation
LEFT OUTER JOIN {{ ref('dim_stations') }} s ON m.station = s.notation
